### ISSUE TITLE
Support multiple template

### ISSUE THREAD

**Issue by wiiznokes** [rust-mobile/xbuild#149]
I just want to call some function of Rust with Kotlin. Rn, the current template create a TauryActivity(?)  and include dioxus by default.

**Comment by wiiznokes** [comment]
Thanks, this is simpler than i expected

**Comment by MarijnS95** [comment]
@wiiznokes note that `rust-android-gradle` is abandoned and that there are some problems getting the built Rust library packaged into the APK consistently. I've spent some time on it once again to make my project(s, just added https://github.com/MarijnS95/AndroidVulkanInterop) work again, in both Groovy and Kotlin DSL:

https://github.com/mozilla/rust-android-gradle/issues/118#issuecomment-1777952460
https://github.com/mozilla/rust-android-gradle/issues/133#issuecomment-1778081960

Besides that I love this setup so far: it's all automated and can be used with a simple `gradle installDebug` from the command-line as well as the full build+run(+debug?) suite in Android Studio.
