### ISSUE TITLE
How to include a native library?

### ISSUE THREAD

**Issue by TheButlah** [rust-mobile/xbuild#151]
I'm trying to use xbuild to compile some code to run on an Oculus Quest, which is android. I need to include the `libopenxr_loader.so` native library, and either dlopen or link against it.

How do I do this with xbuild? I think it should be one of the `runtime_libs`, but this doesn't seem to do anything if I include it in the `manifest.yaml`. Is this functionality supported yet in `xbuild`?

Note: I am using crates.io version `0.2.0`

**Comment by TheButlah** [comment]
I think this functionality was added in #106 back in february, but the last release was in December so the `0.2.0` release was too old to support it.

**Comment by MarijnS95** [comment]
It is probably even better to link it dynamically instead of at runtime via `dlopen()`, and have https://github.com/rust-mobile/xbuild/pull/65/files (that _is_ in the `0.2.0` release) pick up the libraries automatically by scanning `cargo:rustc-link-search=`.
