### ISSUE TITLE
A few questions not addressed by the README

### ISSUE THREAD

**Issue by duckinator** [rust-mobile/xbuild#162]
Hi!

~~I was hoping to use xbuild, since I'm porting a new project to Android and cargo-apk's README points here.~~ (**EDIT:** I figured out all the things blocking me from using xbuild. :3)

I wound up with the following questions, which the README doesn't address:

1. ~~I'm porting an existing Rust app to Android. What tools from `x doctor` are needed? Do I need the clang toolchain? If I do, is the one from the Android NDK sufficient?~~
2. ~~How do I make xbuild find adb?~~
3. How does it handle app manifests?

(**EDIT:** Answered some of my own questions below.)

**Comment by duckinator** [comment]
It seems like a lot of my problems basically boiled down to Windows making it more difficult than was necessary. I switched to Debian for development, and it was far easier to figure things out.

On Debian, `apt install android-sdk-platform-tools adb libssl-dev` and `rustup target add aarch64-linux-android` was enough that I was able to try `x build`.

So, answering some of my own questions:

1. This is enough to at least _get started_ on Debian: clang, clang++, lld, lld-link, rustup, cargo, adb.
2. If it's in your path, xbuild figures it out.

The only thing I'm unsure of now is the app manifest stuff. And I'm _unsure_ if I need to worry about that just yet since my app is fairly early in development.

**Comment by dvc94ch** [comment]
Same process on windows. Windows also has a path and there are various windows package managers, you can take a look at windows ci builds to see how it's done.

As for the manifest you can add a manifest.yml, I think there is an example somewhere.

**Comment by duckinator** [comment]
Yeah, frankly I'm not sure what got me so confused initially. It seemed obvious after I stepped away for a while.

I'm loving xbuild, though. It's really slick. 🙂

**Comment by Gibbz** [comment]
Did you end up find out how to use the manifest? There are no examples or reference to it.... 
@duckinator @dvc94ch
