### ISSUE TITLE
`bash: x: command not found`

### ISSUE THREAD

**Issue by Seldom-SE** [rust-mobile/xbuild#167]
```
[seldom@seldom-endeavour ~]$ cargo install xbuild
    Updating crates.io index
     Ignored package `xbuild v0.2.0` is already installed, use --force to override
[seldom@seldom-endeavour ~]$ x devices
bash: x: command not found
```
I just installed it through cargo and the `x` command isn't found. I didn't see any warnings when installing it or anything

**Comment by Seldom-SE** [comment]
Ok, I found the binary at `~/.cargo/bin/x`, so I can work around it, but I'll leave this open in case you want to look into it

**Comment by dvc94ch** [comment]
You need to add it to PATH. That's required for all binaries installed by cargo.
