### ISSUE TITLE
How to deploy build apk to phone?

### ISSUE THREAD

**Issue by Gibbz** [rust-mobile/xbuild#176]
How do i deploy the built apk to my phone?
I cant find any documentation on how to do this..

**Comment by Doods0** [comment]
`x run --device adb:<id>` ?

**Comment by Gibbz** [comment]
By deploy I mean to automatically copy, then run it.
Thanks

**Comment by Gibbz** [comment]
> `x run --device adb:<id>` ?

Sorry, checked the command, its is what i want! Thanks!
