### ISSUE TITLE
Gradle build on Windows requires admin privilege

### ISSUE THREAD

**Issue by Athosvk** [rust-mobile/xbuild#185]
It seems that when attempting to build with gradle on Windows, the creation of a symlink can fail due to lack of privilege. 
```
[2/3] Build rust `[...]`
[3/3] Create apk
Error: A required privilege is not held by the client. (os error 1314)
```

(Note that these errors are quite hard to find, it would probably help to annote a lot of the system calls with `context`)

It turns out the culprit is this line in `gradle\mod.rs`, when packaging the specified assets from the manifest:

``` rust
std::os::windows::fs::symlink_dir(&path, &target)?;
```

As noted in the [docs](https://doc.rust-lang.org/stable/std/os/windows/fs/fn.symlink_dir.html), dir symlinks require admin privilege., but it's not clear that xbuild requires admin rights for running. If it's not desired to have xbuild run as admin (which I assume it isn't), maybe there should be a fallback for if sym link creation fails?

**Comment by MarijnS95** [comment]
Notice that this code is not avaiable in this repo, but only on a preliminary test-commit of mine on _our fork_: https://github.com/Traverse-Research/xbuild/commit/d5ebb6e6849f0dd225e7c379bec61b1c03d3b86a

Perhaps this isn't the right place to report this.

**Comment by MarijnS95** [comment]
I did however move it out to a PR in https://github.com/rust-mobile/xbuild/pull/146, which is where we should handle this as review?

**Comment by MarijnS95** [comment]
Closing to move into https://github.com/rust-mobile/xbuild/pull/146.
