### ISSUE TITLE
publish to app store

### ISSUE THREAD

**Issue by dvc94ch** [rust-mobile/xbuild#35]

**Comment by dvc94ch** [comment]
@MarijnS95 yeah, closed a bunch of issues. I'm not currently doing any mobile development so I don't have much bandwidth for xbuild. In addition to that I think the scope is too big and we need to figure out exactly what the scope/goals for the project are and more importantly what's out of scope

**Comment by dvc94ch** [comment]
For be the main goal was to 1. not require developers to need a Mac/windows to produce Mac/iOS/windows applications. 2. make it easy for developers to write a rust application and deploy it on all major platforms without needing to be an expert in each.

**Comment by dvc94ch** [comment]
The feedback I've gotten seems to be roughly this:
1. Android developers want more android focus
2. Macos/iOS developers actually want to use xcode
3. We don't support windows well enough for anyone to seriously consider it

**Comment by dvc94ch** [comment]
To properly support all platforms what xbuild would need is a well funded flagship cross platform rust application and a full time developer to properly implement and test features on all platforms. Saddly even if someone where to provide the funding, I'm currently busy with other projects so I wouldn't have the bandwidth anyway.

**Comment by MarijnS95** [comment]
@dvc94ch sure I get that, just wanted to re-close these issues with the right reason to not set false "Closed as completed" expectations :)

Will keep using and contributing to this regardless, and will see what happens in the future. For us the "feedback" is roughly:

1. Should work out of the box as a build tool on Windows and Linux, just like `cargo`. No manual tomfoolery with `winget` (which comes nowhere near a proper package manager on Linux), or the assumption that "only developers with already set-up development environments for Android etc" use it;
2. Needs a few more packaging features that I have PRs open for.

And I might reopen a few issues or file new ones in the future if they become useful/important.

**Comment by MarijnS95** [comment]
I said _Windows **and** Linux_, but on Linux it's typically much easier to acquire these (and have them in `PATH` automatically) via a sane package manager rather than on Windows.

Hence I'm still on the fence whether to only provide these as a Windows-only x86 package, or provide them for Linux as well.

In any case, because of this, I wouldn't add them to the existing xbuild package but create a few new packages that can be (automatically!) downloaded on demand.

**Comment by dvc94ch** [comment]
and what about clang, llvm, java, etc. do we need to package those too?

**Comment by MarijnS95** [comment]
Because you've done such a nice job implementing `apksigner` (and `zipalign`?) We don't need Java, just LLVM/clang and adb.
