### ISSUE TITLE
android app bundles

### ISSUE THREAD

**Issue by dvc94ch** [rust-mobile/xbuild#6]

**Comment by dvc94ch** [comment]
supported via gradle

**Comment by MarijnS95** [comment]
Can't get this done natively? It's probably too complicated for that?

**Comment by dvc94ch** [comment]
it's more like what's the point. android requires java/kotlin/gradle anyway and google is unlikely going to make life easier for us in this regard. every decision they make cements the reliance on these technologies. so I just can't be bothered to put in the work.

**Comment by dvc94ch** [comment]
the app I'm currently working on requires kotlin/gradle anyway to integrate the webview and to implement the qrcode scanner. is there a real use case for native aab's?

**Comment by dvc94ch** [comment]
once thing that I am considering is handling aab signing in xbuild. aab's are signed differently than apks.
