### ISSUE TITLE
Embed assets in Android APKs

### ISSUE THREAD

**Issue by MarijnS95** [rust-mobile/xbuild#82]
Before diving into the implementation for this, what's the best way to embed assets on Android nowadays?

1. We can pack them up in the `.apk` and read (or map if packed uncompressed) them at runtime using `AAsset`;
2. Use [OBB files](https://developer.android.com/google/play/expansion-files);
3. Something with app bundles they have a similar concept to "OBB extension files" named "asset packs" or "[Play Asset Delivery](https://developer.android.com/guide/playcore/asset-delivery)" to separate (cross-platform) data from per-platform code.

@dvc94ch Does `xbuild` support anything for this nowadays, and if not, what do you reckon is the best way forward?

**Comment by dvc94ch** [comment]
flutter uses option 1. but open to suggestions. I don't have a strong opinion, but will probably need to look into this problem soon for my own app

**Comment by MarijnS95** [comment]
I'd be fine to do 1. since that's nice-to-have anyway for smaller assets and quick solutions, before diving into the crevices of app bundles. OBB seems to be deprecated, better not spend time on that.

**Comment by dvc94ch** [comment]
I think there are two valid ways of doing this. You embed all assets in the binary using `include_dir!` (what I'm currently doing) or integrate with platform specific packaging. Would like to see a crate for that with some support in xbuild if needed, but probably won't be tackling this myself.

See how to handle this on macos here [0] with ios likely being very similar.

- [0] https://github.com/DioxusLabs/dioxus/blob/master/packages/desktop/src/protocol.rs#L104

**Comment by dvc94ch** [comment]
closing this for now as out of scope

**Comment by MarijnS95** [comment]
Using it for my own tracking purposes.

**Comment by NiklasEi** [comment]
Are there any news on this?
I am trying to move my bevy app from `cargo-apk` to `xbuild` to get support for building app bundles. The app builds and opens up, but the apk does not contain the assets. `cargo apk` puts them in the apk based on the path provided in the Cargo.toml. I guess that's option 1?

**Comment by MarijnS95** [comment]
@NiklasEi I'm still using my [`assets`](https://github.com/MarijnS95/xbuild/tree/assets) branch on a daily basis (seems I forgot to link that here) and am eyeing a PR sooner rather than later, after improving compression support.

This is only option 1. though; separately I dearly wish to add native `.aab` support but that's further down the pipeline. Note that `xbuild` doesn't yet support that, except when using the `gradle` backend (otherwise it (used to?) generate `.aab` files which were just APKs).

**Comment by NiklasEi** [comment]
> I'm still using my [assets](https://github.com/MarijnS95/xbuild/tree/assets) branch on a daily basis (seems I forgot to link that here) and am eyeing a PR sooner rather than later, after improving compression support.

Awesome, just what I needed! I went ahead and added support for globs in asset paths: MarijnS95/xbuild#1
Now my bevy app runs fine with 
```  assets: 
    - "../assets/*"
```

**Comment by jkelleyrtp** [comment]
Hi, I'm trying to add support to manganis (dioxus' new linker-based asset solution) 

One of the things we need to do is dynamically canonicalize the assets per-platform. I'm trying to get that working with xbuild.

I see #122 but no examples on reading from that directory. Is it just `std::fs::read("assets/blah.txt")`?

**Comment by MarijnS95** [comment]
@jkelleyrtp that's about what `zip.add_file()` is supposed to do, based on the difference between the `asset` variable and the `file_name`. `add_directory()` does this recursively.

As documented, only the `file_name()` (the last component of the given path) is put in the APK. So specifying an asset `foo/bar/blah.txt` gives you `assets/blah.txt` in the APK (and `foo` gives you `assets/foo/bar/blah.txt` together with any other files inside `foo/`). If you need anything else, right now the only option is to build a directory tree on the file system (maybe with symlinks?).

if you need anything more sophisticated (i.e. an optional `target:` parameter) in `manifest.yaml`, feel free to contribute :)
